tokio-rs/valuable

valuable-derive/src/expand.rs
valuable/src/enumerable.rs
valuable/src/value.rs
valuable/tests/derive.rs
valuable/tests/enumerable.rs

Closes #2 
This also adds support for derive Valuable for tuple struct.
From:
```rust
#[derive(Valuable)]
enum Enum {
Struct { x: &'static str },
Tuple(u8),
Unit,
}
```
To:
```rust
const _: () = {
static Enum_Struct_FIELDS: &[::valuable::field::NamedField<'static>] =&[
::valuable::field::NamedField::new("x"),
];
static Enum_VARIANTS: &[::valuable::VariantDef<'static>] = &[
::valuable::VariantDef {
name: "Struct",
fields: ::valuable::field::Fields::NamedStatic(Enum_Struct_FIELDS),
is_dynamic: false,
},
::valuable::VariantDef {
name: "Tuple",
fields: ::valuable::field::Fields::Unnamed,
is_dynamic: false,
},
::valuable::VariantDef {
name: "Unit",
fields: ::valuable::field::Fields::Unnamed,
is_dynamic: false,
},
];
impl ::valuable::Enumerable for Enum {
fn definition(&self) -> …
```

derive Valuable for enum

---

tests/tests/enumerable.rs
valuable-derive/src/expand.rs
valuable/src/enumerable.rs

Probably this was missed in https://github.com/tokio-rs/valuable/commit/c280d84eec818bcf5abbfc4d715dd328edce5e71.

Make Variant fields private

---

valuable/Cargo.toml
valuable/src/enumerable.rs
valuable/src/listable.rs
valuable/src/mappable.rs
valuable/src/slice.rs
valuable/src/structable.rs
valuable/src/valuable.rs
valuable/src/value.rs

- impl valuable traits (Valuable, Mappable, Listable, etc.) for Box, Rc, Arc, reference
- impl Valuable/Mappable for BTreeMap
- impl Valuable/Listable for array ([T; N])
- fix build error on no_std + alloc
The current master fails to build on no_std + alloc (I noticed this problem when I was implementing valuable traits for Box). This patch fixes it.
```console
cargo build --target thumbv7m-none-eabi --no-default-features --features alloc,derive -p valuable
```

impl valuable traits for more types, fix build error on no_std + alloc

---

.github/workflows/ci.yml
Cargo.toml
valuable/src/enumerable.rs
valuable/src/slice.rs

Fixes build error by the way mentioned in https://github.com/tokio-rs/valuable/pull/10#discussion_r630179884.
> print only variant name when alloc feature is disabled? (like the following)
> 
> ```rust
> #[cfg(feature = "alloc")]
> let name = format!("{}::{}", self.name, variant.name());
> #[cfg(not(feature = "alloc"))]
> let name = variant.name();
> ```

Fix build error when alloc feature is disabled

---

valuable/src/listable.rs
valuable/src/valuable.rs

remaining [std::collections](https://doc.rust-lang.org/nightly/std/collections/index.html) types and some types:
- `impl<T: Valuable> Listable for Rc<[T]>`
- `impl<T: Valuable> Listable for Arc<[T]>`
- `impl<T: Valuable> Listable for VecDeque<T>`
- `impl<T: Valuable> Listable for LinkedList<T>`
- `impl<T: Valuable + Ord> Listable for BinaryHeap<T>`
- `impl<T: Valuable + Ord> Listable for BTreeSet<T>`
- `impl<T: Valuable + Eq + Hash, H: BuildHasher> Listable for HashSet<T, H>`

impl Listable for std collections

---

valuable/src/valuable.rs

all [std::num](https://doc.rust-lang.org/nightly/core/num/index.html) types:
- `NonZeroI8`
- `NonZeroI16`
- `NonZeroI32`
- `NonZeroI64`
- `NonZeroI128`
- `NonZeroIsize`
- `NonZeroU8`
- `NonZeroU16`
- `NonZeroU32`
- `NonZeroU64`
- `NonZeroU128`
- `NonZeroUsize`
- `Wrapping<T: Valuable>`

impl Valuable for std num types

---

valuable/src/listable.rs

`impl Valuable for Arc<[T]>` is added in #13, but when that PR was opened, #12 had not yet been merged, so #13 did not handle targets that do not support atomic CAS.
As a result, the CI of the master branch is currently failing:
```
error[E0433]: failed to resolve: could not find `sync` in `alloc`
--> valuable/src/listable.rs:73:26
|
73 |     (T: Valuable) alloc::sync::Arc<[T]>,
|                          ^^^^ could not find `sync` in `alloc`
```
https://github.com/tokio-rs/valuable/runs/2560992823?check_suite_focus=true

Fix build error on master

---

tests/src/visit_count.rs
tests/tests/listable.rs
valuable/src/listable.rs
valuable/src/slice.rs
valuable/src/valuable.rs
valuable/src/value.rs
valuable/src/visit.rs

Instead of always going via visit_slice, a visit_primitive_slice method
is added. Primitive slices go via there. Non-primitive slices call
`visit_item`.

tweak listable visit API

---

tests/src/hello_world.rs
tests/tests/enumerable.rs
tests/tests/structable.rs
valuable-derive/src/expand.rs
valuable/benches/structable.rs
valuable/examples/hello_world.rs
valuable/src/enumerable.rs
valuable/src/field.rs
valuable/src/lib.rs
valuable/src/structable.rs

Both definition types now are enums between Static and Dynamic
definitions. This better supports serde support.

switch StructDef and EnumDef to enums

---

tests/src/hello_world.rs
tests/tests/enumerable.rs
tests/tests/structable.rs
valuable-derive/src/expand.rs
valuable/benches/structable.rs
valuable/examples/hello_world.rs
valuable/src/lib.rs

Expose `fields::*` types at the root. Given the small number of types,
having a separate module is not worth it.

flatten `fields` mod

---

tests/tests/derive.rs
tests/tests/named_values.rs
valuable/src/enumerable.rs
valuable/src/listable.rs
valuable/src/mappable.rs
valuable/src/structable.rs
valuable/src/valuable.rs

Without this, we cannot use `derive(Valuable)` on structs such as:
```rust
#[derive(Valuable)]
struct Test<'a> {
string: &'a mut String,
}
```
```text
error[E0277]: the trait bound `&mut std::string::String: Valuable` is not satisfied
--> tests/tests/derive.rs:43:10
|
43 | #[derive(Valuable)]
|          ^^^^^^^^ the trait `Valuable` is not implemented for `&mut std::string::String`
|
= help: the following implementations were found:
<std::string::String as Valuable>
= note: `Valuable` is implemented for `&std::string::String`, but not for `&mut std::string::String`
= note: required by `as_value`
= note: this error originates in the derive macro `Valuable` (in Nightly builds, run with -Z macro-backtrace for more info)
```
(As for bad diagnostics of valuable-derive, I will fix them in …

impl valuable traits for mutable reference

---

tests/Cargo.toml
tests/tests/derive.rs
tests/tests/ui/not_valuable.rs
tests/tests/ui/not_valuable.stderr
valuable-derive/src/expand.rs

follow-up #30
Before:
```text
error[E0277]: the trait bound `S: Valuable` is not satisfied
--> valuable/examples/not_valuable.rs:5:10
|
5 | #[derive(Valuable)]
|          ^^^^^^^^ the trait `Valuable` is not implemented for `S`
|
= note: required because of the requirements on the impl of `Valuable` for `Option<S>`
= note: required by `as_value`
= note: this error originates in the derive macro `Valuable` (in Nightly builds, run with -Z macro-backtrace for more info)
```
After:
```text
error[E0277]: the trait bound `S: Valuable` is not satisfied
--> valuable/examples/not_valuable.rs:7:8
|
7 |     f: Option<S>,
|        ^^^^^^^^^ the trait `Valuable` is not implemented for `S`
|
= note: required because of the requirements on the impl of `Valuable` for `Option<S>`
= note: required by …
```

derive: improve diagnostics when field does not implement Valuable

---

tests/tests/tuplable.rs
tests/tests/value.rs
valuable-serde/src/lib.rs
valuable/src/lib.rs
valuable/src/structable.rs
valuable/src/tuplable.rs
valuable/src/valuable.rs
valuable/src/value.rs

A proposal for handling tuples. If this looks like a good direction, I will finish it up (docs / tests). I would also probably change `Value::Unit` -> `Value::Tuplable` and add `Value::Some` and `Value::None`.

add Tuplable

---

valuable-serde/src/lib.rs
valuable-serde/tests/test.rs

serde: support tuple

---

valuable/no_atomic.rs

```console 
$ ./ci/no_atomic.sh
$ git --no-pager diff
diff --git a/valuable/no_atomic.rs b/valuable/no_atomic.rs
index 832a60a..f644a11 100644
--- a/valuable/no_atomic.rs
+++ b/valuable/no_atomic.rs
@@ -3,6 +3,8 @@
const NO_ATOMIC_CAS: &[&str] = &[
"avr-unknown-gnu-atmega328",
+    "bpfeb-unknown-none",
+    "bpfel-unknown-none",
"msp430-none-elf",
"riscv32i-unknown-none-elf",
"riscv32imc-unknown-none-elf",
$ git checkout -b taiki-e/no-atomic
$ git add valuable/no_atomic.rs
$ git commit -m "Update list of targets that do not support atomic CAS"
```

Update list of targets that do not support atomic CAS

---

valuable/src/enumerable.rs
valuable/src/listable.rs
valuable/src/mappable.rs
valuable/src/structable.rs
valuable/src/tuplable.rs
valuable/src/valuable.rs
valuable/src/visit.rs

- impl `Tuplable` for Box, Rc, Arc, reference, mutable reference
- impl `Visit` for Box and mutable reference (I encountered a case where it was desirable to have this, during writing valuable value pointer macro)
- use macro for more trait impls

impl valuable traits for more types

---

tests/tests/enumerable.rs
tests/tests/listable.rs
tests/tests/value.rs
valuable/examples/hello_world.rs
valuable/src/slice.rs
valuable/src/value.rs
valuable/src/visit.rs

This branch contains a number of small fixes for several clippy lints:
* 00f5715 Add `Slice::is_empty()` method
Clippy lints about types which have a public `len` method but no 
corresponding `is_empty` method. Therefore, I've added an `is_empty` 
method that returns `true` if `self.len() > 0`.
Since this is a new API that we'll have to support, it would also be 
fine to solve this by _not_ adding the method and just suppressing the 
warning...but it seems worth having for consistency with the
underlying slice's methods? And, I don't see how this could really
pose a forward-compatibility hazard, since `Slice` is...always going
to be backed by an actual slice...
* fb8c985 don't call `clone` on `Value`, which is `Copy`
* dd3018e fix clippy lints about static lifetimes
Clippy lints on …

Fix several clippy lints

---

valuable/src/enumerable.rs

Closes #18
This PR adds `Valuable` and `Enumerable` implementations for 
`Result<T, E>` where `T` and `E` are `Valuable`.
@carllerche's comment in https://github.com/tokio-rs/valuable/issues/18#issue-890512640 suggested
that `Result`s should "flatten" the inner values rather than
implementing `Enumerable`.
However, this PR _does_ implement `Enumerable`. This is because simply
flattening `Result`s to the `Ok` or `Err` value would make it impossible
for the `Visit`or to determine if a given `Result` is an `Ok` or `Err`
value, which seems quite important for some use cases. As I described in
https://github.com/tokio-rs/valuable/issues/18#issuecomment-938905149:
> If the `Err` side of a `Result` is _not_ a `&(dyn std::error::Err + static)`,
> there's no way for the visitor to know if the …

Implement `Valuable` and `Enumerable` for `Result<T, E>`

---

tests/tests/enumerable.rs
tests/tests/structable.rs
valuable-derive/src/expand.rs
valuable-serde/src/lib.rs
valuable-serde/tests/test.rs
valuable/src/enumerable.rs
valuable/src/field.rs
valuable/src/structable.rs

Closes #36
Currently, there is no way to determine the number of fields in a tuple
struct or tuple-like enum variant without actually visiting the fields.
On the other hand, it _is_ possible to get the number of fields from a
struct or struct-like enum variant, by calling `.len()` on the slice of
`NamedFields` in `Fields::Named`.
It seems like both `Fields::Unnamed` _and_ `Fields::Named` probably
ought to have a way to determine the number of fields. I can imagine
use-cases where (say) a serializer wants to know the number of fields
before actually visiting them, in order to pre-allocate storage, or emit
a length delimiter, or something.
This branch changes `Fields::Unnamed` to store a `usize` number of
fields. It also adds `Fields::len` and `Fields::is_empty` methods to
`Fields`, …

fields: Add the number of fields to `Fields::Unnamed`

---

tests/tests/ui/not_valuable.stderr

Some error messages have been changed in the new stable.
This fixes CI failure: https://github.com/tokio-rs/valuable/runs/4501186256?check_suite_focus=true

Update ui test to Rust 1.57

---

valuable/src/structable.rs

`StructDef` is intended to be used from a static context, so the
methods should be `const fn`.

make `StructDef` methods `const fn`

---

.github/workflows/ci.yml
valuable/Cargo.toml
valuable/src/lib.rs

Replaces #74.
refs: https://github.com/rust-lang/rust/pull/89596, https://github.com/rust-lang/rust/pull/90502
Closes: #74

Enable doc_cfg and doc_auto_cfg features on docs.rs

---

tests/tests/ui/not_valuable.stderr

Looks like the error message changed slightly, which broke my CI build
for PR #83: 
https://github.com/tokio-rs/valuable/runs/4957336428?check_suite_focus=true
This commit contains the result of a `TRYBUILD=overwrite` run, which
should fix CI.

tests: update UI tests for Rust 1.58.1

---

valuable-serde/src/lib.rs

Currently, `valuable-serde` handles `Value::Error` variants incorrectly.
When `valuable-serde` encounters a `Value::Error`, it returns the error
immediately as a serialization error:
https://github.com/tokio-rs/valuable/blob/1fc2ad50fcae7fc0da81dc40a385c235636ba525/valuable-serde/src/lib.rs#L267
This is _not_ correct. If a `serde` serializer returns an error, this
means something has gone wrong while serializing a value. Returning an
error makes the serialization fail. However, this is *not* what
`valuable`'s `Value::Error` means. `Value::Error` represents that we are
_recording a value which happens to be an `Error`_, not that something
went wrong _while_ recording the value. This means that `valuable-serde`
will currently return an `Error` (indicating that serialization failed)
any time …

serde: serialize `dyn Error` `Value`s using `collect_str`

---

valuable-serde/src/lib.rs
valuable-serde/tests/test.rs

This PR changes `valuable-serde`'s recording of `dyn Error` values to
record the error as a `serde` struct with `message` and `source` fields.
This way, we can serialize errors with source chains more nicely.
When the backtrace support for `std::error::Error` is stable, we could
also record backtraces as a field. We could even consider adding a build
script to detect the nightly compiler and conditionally enable a `cfg`
for backtrace support, but that seems better left to a follow-up.

serde: record errors as a struct with fields for sources

---

valuable/src/mappable.rs

With this MR I be able to use `valuable` for `HashMap` with different hasher.

Make implementation Valuable for HashMap more generic.

---

.github/workflows/ci.yml
tests/Cargo.toml
tests/tests/listable.rs
tests/tests/ui/not_valuable.stderr
tests/tests/value.rs
valuable-derive/Cargo.toml
valuable-serde/Cargo.toml
valuable/Cargo.toml
valuable/src/value.rs

Our MSRV is 1.56 that Rust 2021 was stabilized.
(The first commit is a CI fix from #119)

Migrate to Rust 2021

---

valuable-derive/src/expand.rs

I am currently using `valuable` on a project that has most clippy lints enabled, and it is showing warnings because it uses direct array indexing to access the fields on the generated macro code. Unfortunately, there's no way to ignore it directly, as it gets "imported" to application code on macro expansion.
This PR adds `clippy::indexing_slicing` to the listing of ignored lints.

Add clippy::indexing_slicing to the list of ignored lints

---

valuable-derive/src/expand.rs

Since https://github.com/rust-lang/rust/pull/120185, this helps the generated code to not be instrumented.
Fixes https://github.com/taiki-e/cargo-llvm-cov/issues/397.

derive: Use #[automatically_derived] on generated impls

---

CHANGELOG.md
tests/tests/ui/not_valuable.stderr
valuable-derive/Cargo.toml
valuable-serde/CHANGELOG.md
valuable-serde/Cargo.toml
valuable/Cargo.toml

- Make `Valuable` implementation for `HashMap` more generic (#112)
- Bump MSRV to 1.56 (#118)
- derive: update syn to 2.0 (#118)
- derive: implement `#[valuable]` attributes (#75)
- derive: use `#[automatically_derived]` on generated impls to improve coverage support (#136)
- Serialize `dyn Error` Values as a struct with fields for sources (#92)
---
Except for https://crates.io/crates/valuable, the core team does not have the permission to publish these crates, so I cannot publish them at this time:
@carllerche: Could you give the core team permission to publish this crate?
@hawkw: Could you give the core team permission to publish this crate?
---
Closes #135

Prepare valuable, valuable-derive, and valuable-serde 0.1.1
